version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@1.0.0

jobs:
  continue:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Checkout source via HTTPS
          command: |
            git clone "https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git" .
            git checkout "$CIRCLE_SHA1"
      - continuation/continue:
          configuration_path: .rs-ci/.circleci/config.yml

workflows:
  setup:
    jobs:
      - continue
